from django.conf.urls import url

from .views import category_views,\
    esrb_views,\
    game_views, \
    genre_views, \
    platform_views, \
    registration_view, \
    authorisation_view, \
    logout_view

app_name = 'catalog'
urlpatterns = [
    url(
        r'^$',
        authorisation_view.LoginFormView.as_view(),
        name='login'
    ),
    url(r'^index/$', game_views.IndexView.as_view(), name='index'),
    url(
        r'^register/$',
        registration_view.RegistrationFormView.as_view(),
        name='register'
    ),
    url(
        r'^logout/$',
        logout_view.LogoutView.as_view(),
        name='logout'
    ),
    url(
        r'^category-list/$',
        category_views.CategoryListView.as_view(),
        name='category-list'
    ),
    url(
        r'^genre-list/$',
        genre_views.GenreListView.as_view(),
        name='genre-list'
    ),
    url(
        r'^esrb-list/$',
        esrb_views.ESRBListView.as_view(),
        name='esrb-list'
    ),
    url(
        r'^platform-list/$',
        platform_views.PlatformListView.as_view(),
        name='platform-list'
    ),
    url(
        r'^game-detail/(?P<pk>[0-9]+)/$',
        game_views.GameDetailView.as_view(),
        name='game-detail'
    ),
    url(
        r'^category-detail/(?P<pk>[0-9]+)/$',
        category_views.CategoryDetailView.as_view(),
        name='category-detail'
    ),
    url(
        r'^genre-detail/(?P<pk>[0-9]+)/$',
        genre_views.GenreDetailView.as_view(),
        name='genre-detail'
    ),
    url(
        r'^platform-detail/(?P<pk>[0-9]+)/$',
        platform_views.PlatformDetailView.as_view(),
        name='platform-detail'
    ),
    url(
        r'^esrb-detail/(?P<pk>[0-9]+)/$',
        esrb_views.ESRBDetailView.as_view(),
        name='esrb-detail'
    ),
    url(
        r'^game-add-form/$',
        game_views.GameCreateView.as_view(),
        name='game-add-form'
    ),
    url(
        r'^category-add-form/$',
        category_views.CategoryCreateView.as_view(),
        name='category-add-form'
    ),
    url(
        r'^genre-add-form/$',
        genre_views.GenreCreateView.as_view(),
        name='genre-add-form'
    ),
    url(
        r'^platform-add-form/$',
        platform_views.PlatformCreateView.as_view(),
        name='platform-add-form'
    ),
    url(
        r'^esrb-add-form/$',
        esrb_views.ESRBCreateView.as_view(),
        name='esrb-add-form'
    ),
    url(
        r'^game-delete/(?P<pk>\d+)$',
        game_views.GameDeleteView.as_view(),
        name='game-delete'
    ),
    url(
        r'^genre-delete/(?P<pk>\d+)$',
        genre_views.GenreDeleteView.as_view(),
        name='genre-delete'
    ),
    url(
        r'^platform-delete/(?P<pk>\d+)$',
        platform_views.PlatformDeleteView.as_view(),
        name='platform-delete'
    ),
    url(
        r'^category-delete/(?P<pk>\d+)$',
        category_views.CategoryDeleteView.as_view(),
        name='category-delete'
    ),
    url(
        r'^esrb-delete/(?P<pk>\d+)$',
        esrb_views.ESRBDeleteView.as_view(),
        name='esrb-delete'
    ),
    url(
        r'^game-update-form/(?P<pk>\d+)$',
        game_views.GameUpdateView.as_view(),
        name='game-update-form'
    ),
    url(
        r'^category-update-form/(?P<pk>\d+)$',
        category_views.CategoryUpdateView.as_view(),
        name='category-update-form'
    ),
    url(
        r'^esrb-update-form/(?P<pk>\d+)$',
        esrb_views.ESRBUpdateView.as_view(),
        name='esrb-update-form'
    ),
    url(
        r'^genre-update-form/(?P<pk>\d+)$',
        genre_views.GenreUpdateView.as_view(),
        name='genre-update-form'
    ),
    url(
        r'^platform-update-form/(?P<pk>\d+)$',
        platform_views.PlatformUpdateView.as_view(),
        name='platform-update-form'
    ),
]
